"""Init unified user

Revision ID: c7271efd78e4
Revises: 
Create Date: 2026-03-16 08:43:35.564946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7271efd78e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('qc_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_mode', sa.String(length=50), nullable=False),
    sa.Column('default_max_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('ordering', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['qc_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_criteria_code'), 'qc_criteria', ['code'], unique=True)
    op.create_index(op.f('ix_qc_criteria_id'), 'qc_criteria', ['id'], unique=False)
    op.create_table('qc_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_forms_code'), 'qc_forms', ['code'], unique=True)
    op.create_index(op.f('ix_qc_forms_id'), 'qc_forms', ['id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('shortAddress', sa.String(length=255), nullable=True),
    sa.Column('storeId', sa.String(length=50), nullable=True),
    sa.Column('brandId', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_brandId'), 'stores', ['brandId'], unique=False)
    op.create_index(op.f('ix_stores_code'), 'stores', ['code'], unique=True)
    op.create_index(op.f('ix_stores_id'), 'stores', ['id'], unique=False)
    op.create_index(op.f('ix_stores_storeId'), 'stores', ['storeId'], unique=False)
    op.create_table('qc_form_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('pass_rule', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['qc_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_form_versions_form_id'), 'qc_form_versions', ['form_id'], unique=False)
    op.create_index(op.f('ix_qc_form_versions_id'), 'qc_form_versions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('suite_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('qc_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('criteria_states', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_drafts_auditor_id'), 'qc_drafts', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_qc_drafts_id'), 'qc_drafts', ['id'], unique=False)
    op.create_index(op.f('ix_qc_drafts_store_id'), 'qc_drafts', ['store_id'], unique=False)
    op.create_table('qc_form_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['qc_criteria.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['qc_form_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_form_criteria_criterion_id'), 'qc_form_criteria', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_qc_form_criteria_form_version_id'), 'qc_form_criteria', ['form_version_id'], unique=False)
    op.create_index(op.f('ix_qc_form_criteria_id'), 'qc_form_criteria', ['id'], unique=False)
    op.create_table('qc_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('form_version_id', sa.Integer(), nullable=False),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('audited_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_version_id'], ['qc_form_versions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_sessions_auditor_id'), 'qc_sessions', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_qc_sessions_code'), 'qc_sessions', ['code'], unique=True)
    op.create_index(op.f('ix_qc_sessions_form_version_id'), 'qc_sessions', ['form_version_id'], unique=False)
    op.create_index(op.f('ix_qc_sessions_id'), 'qc_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_qc_sessions_store_id'), 'qc_sessions', ['store_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('responsible_department_id', sa.Integer(), nullable=False),
    sa.Column('ticket_category_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('attachments_media', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_handler_id'), 'tickets', ['handler_id'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_requester_id'), 'tickets', ['requester_id'], unique=False)
    op.create_index(op.f('ix_tickets_responsible_department_id'), 'tickets', ['responsible_department_id'], unique=False)
    op.create_index(op.f('ix_tickets_store_id'), 'tickets', ['store_id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_code'), 'tickets', ['ticket_code'], unique=True)
    op.create_table('user_stores',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'store_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_ticket_id'), 'notifications', ['ticket_id'], unique=False)
    op.create_table('qc_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=True),
    sa.Column('criterion_code', sa.String(length=50), nullable=True),
    sa.Column('criterion_name', sa.String(length=255), nullable=False),
    sa.Column('mode_snapshot', sa.String(length=50), nullable=False),
    sa.Column('max_score_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applicable', sa.Boolean(), nullable=True),
    sa.Column('requires_fix', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['qc_criteria.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['qc_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_session_items_criterion_id'), 'qc_session_items', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_qc_session_items_id'), 'qc_session_items', ['id'], unique=False)
    op.create_index(op.f('ix_qc_session_items_session_id'), 'qc_session_items', ['session_id'], unique=False)
    op.create_table('ticket_assignees',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    op.create_table('ticket_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_logs_id'), 'ticket_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_logs_sender_id'), 'ticket_logs', ['sender_id'], unique=False)
    op.create_index(op.f('ix_ticket_logs_ticket_id'), 'ticket_logs', ['ticket_id'], unique=False)
    op.create_table('qc_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finding_code', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('session_item_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('criterion_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('corrective_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('meta_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['qc_sessions.id'], ),
    sa.ForeignKeyConstraint(['session_item_id'], ['qc_session_items.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_findings_assignee_id'), 'qc_findings', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_qc_findings_finding_code'), 'qc_findings', ['finding_code'], unique=True)
    op.create_index(op.f('ix_qc_findings_id'), 'qc_findings', ['id'], unique=False)
    op.create_index(op.f('ix_qc_findings_session_id'), 'qc_findings', ['session_id'], unique=False)
    op.create_index(op.f('ix_qc_findings_session_item_id'), 'qc_findings', ['session_item_id'], unique=False)
    op.create_index(op.f('ix_qc_findings_store_id'), 'qc_findings', ['store_id'], unique=False)
    op.create_index(op.f('ix_qc_findings_verifier_id'), 'qc_findings', ['verifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qc_findings_verifier_id'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_store_id'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_session_item_id'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_session_id'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_id'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_finding_code'), table_name='qc_findings')
    op.drop_index(op.f('ix_qc_findings_assignee_id'), table_name='qc_findings')
    op.drop_table('qc_findings')
    op.drop_index(op.f('ix_ticket_logs_ticket_id'), table_name='ticket_logs')
    op.drop_index(op.f('ix_ticket_logs_sender_id'), table_name='ticket_logs')
    op.drop_index(op.f('ix_ticket_logs_id'), table_name='ticket_logs')
    op.drop_table('ticket_logs')
    op.drop_table('ticket_assignees')
    op.drop_index(op.f('ix_qc_session_items_session_id'), table_name='qc_session_items')
    op.drop_index(op.f('ix_qc_session_items_id'), table_name='qc_session_items')
    op.drop_index(op.f('ix_qc_session_items_criterion_id'), table_name='qc_session_items')
    op.drop_table('qc_session_items')
    op.drop_index(op.f('ix_notifications_ticket_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('user_stores')
    op.drop_index(op.f('ix_tickets_ticket_code'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_store_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_responsible_department_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_requester_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_handler_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_qc_sessions_store_id'), table_name='qc_sessions')
    op.drop_index(op.f('ix_qc_sessions_id'), table_name='qc_sessions')
    op.drop_index(op.f('ix_qc_sessions_form_version_id'), table_name='qc_sessions')
    op.drop_index(op.f('ix_qc_sessions_code'), table_name='qc_sessions')
    op.drop_index(op.f('ix_qc_sessions_auditor_id'), table_name='qc_sessions')
    op.drop_table('qc_sessions')
    op.drop_index(op.f('ix_qc_form_criteria_id'), table_name='qc_form_criteria')
    op.drop_index(op.f('ix_qc_form_criteria_form_version_id'), table_name='qc_form_criteria')
    op.drop_index(op.f('ix_qc_form_criteria_criterion_id'), table_name='qc_form_criteria')
    op.drop_table('qc_form_criteria')
    op.drop_index(op.f('ix_qc_drafts_store_id'), table_name='qc_drafts')
    op.drop_index(op.f('ix_qc_drafts_id'), table_name='qc_drafts')
    op.drop_index(op.f('ix_qc_drafts_auditor_id'), table_name='qc_drafts')
    op.drop_table('qc_drafts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_qc_form_versions_id'), table_name='qc_form_versions')
    op.drop_index(op.f('ix_qc_form_versions_form_id'), table_name='qc_form_versions')
    op.drop_table('qc_form_versions')
    op.drop_index(op.f('ix_stores_storeId'), table_name='stores')
    op.drop_index(op.f('ix_stores_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_code'), table_name='stores')
    op.drop_index(op.f('ix_stores_brandId'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_qc_forms_id'), table_name='qc_forms')
    op.drop_index(op.f('ix_qc_forms_code'), table_name='qc_forms')
    op.drop_table('qc_forms')
    op.drop_index(op.f('ix_qc_criteria_id'), table_name='qc_criteria')
    op.drop_index(op.f('ix_qc_criteria_code'), table_name='qc_criteria')
    op.drop_table('qc_criteria')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
